all:
	+make -C ../

eog:
	eog ../out.png

force:
	make clean all run eog

test:
	make run eog

lib:
	make lib -C ../

run:
	make run -C ../

vg:
	make vg -C ../

gdb:
	make gdb -C ../

killall:
	make killall -C ../

clean:
	make clean -C ../
